-- ============================================================
--  CommAssess — Mock Call Topics (7 scenarios from Word doc)
--  Paste into: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- Step 1: Add bot_script column if not already done
ALTER TABLE topics ADD COLUMN IF NOT EXISTS bot_script JSONB NOT NULL DEFAULT '[]';

-- Step 2: Insert the 7 Mock Call topics
-- (If you already inserted "Pledged Stocks" manually, delete that row
--  from Admin → Topics after running this.)

-- ── Mock Call 1 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'Account Modification – Name Change Document Rejection',
  'A client submitted an Account Modification Form (Name Change). The documents were verified internally and couriered, but were later rejected by the processing team. The client calls seeking clarification, as the documents were sent only after internal verification.',
  'You receive an inbound call. The client is frustrated that their documents were declared valid during the internal check but later rejected by the verification team after couriering.',
  '["Stay calm and professional throughout", "Acknowledge the client''s frustration with empathy", "Explain the internal vs external verification process clearly", "Offer a concrete resolution path (re-submission support, escalation)", "Confirm next steps in writing before ending the call"]'::jsonb,
  '["I was told by your team that my documents were perfectly fine before I couriered them. Now you''re saying they''re rejected — can you explain how that even happens?", "Do you have any idea how long it takes to get these documents arranged and couriered? Who is going to compensate me for that effort and cost?", "I specifically called and confirmed before sending. Do your teams not talk to each other?", "I don''t want to hear ''I''ll check and get back to you'' — I''ve been patient long enough. What is the exact reason my documents were rejected?", "Is there a written record of my conversation with your team when they verified my documents? I want that pulled up right now.", "Who is accountable here — the person who told me the documents were fine, or the person who rejected them? Someone has to own this.", "How many times am I expected to follow up on something that was your team''s error in the first place?", "If the verification team has a different checklist than whoever I spoke to earlier, why isn''t that communicated to the customer upfront?", "Why wasn''t I notified immediately when the rejection happened? I had to call in myself to find out — is that standard practice?", "Is there a quality check before a rejection is issued? Or does one person just get to decide and send it back without review?", "What is the guaranteed turnaround time for this to be resolved — not an estimate, a commitment?", "I am not couriering documents a second time at my own expense because of your internal miscommunication. What arrangements will you make?", "Can you escalate this to a supervisor right now? I want someone with authority to handle this, not just log a ticket.", "If this isn''t resolved by a specific date, what is your escalation path? I want names and contact details.", "I want a written confirmation of whatever resolution you''re promising me right now. Can you send that over email before I hang up?", "This has already delayed a critical process on my end. If there are any financial implications from this delay, will your organisation be taking responsibility?"]'::jsonb,
  NOW()
);

-- ── Mock Call 2 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'Name Change – Client Refuses to Submit Gazette Notification',
  'A client requests a name change on their account. The Gazette notification is mandatory for processing. The client refuses to submit it, claiming other documents (Aadhaar, PAN, passport) should be sufficient, and insists on an exception.',
  'You receive an inbound call. The client wants their name updated on the account but is unwilling to provide the required Gazette notification, and is escalating the situation.',
  '["Empathetically acknowledge the inconvenience", "Clearly explain the regulatory/policy reason for the Gazette requirement", "Guide the client on how to obtain a Gazette notification if possible", "Offer escalation path without overpromising exceptions", "Close professionally with a clear next step"]'::jsonb,
  '["I''ve been your customer for so many years — isn''t my word enough? Why do I need to prove my own name to you?", "I have my Aadhaar, PAN, and passport all updated with my new name. Why isn''t that sufficient? Why specifically a Gazette notification?", "Other institutions have updated my name without a Gazette — why is your process so outdated and complicated?", "Who made this rule? Is this a government regulation or just your company''s internal policy? Show me where it''s written.", "Can''t you just flag my account and make an exception this one time? I''m not asking you to do anything illegal.", "Is there a senior authority or department that can approve a name change without the Gazette? I want to speak to them.", "What if I sign an indemnity or a self-declaration — would that not be enough instead of the Gazette?", "Other customers must have faced this problem — what alternative did you offer them?", "Do you understand how difficult it is to get a Gazette notification? It takes months and costs money — is that fair to the customer?", "So you''re telling me that until I get this one document, my account will keep showing my old name? What kind of service is that?", "I am a senior citizen and it is practically impossible for me to get a Gazette notification. What is your solution for that?", "I''ll take this up with the consumer forum if you can''t find a solution. Is that really where you want this to go?", "Can you tell me exactly which government authority issues a Gazette notification and what the process is? If you''re mandating it, you should be able to guide me.", "Is there a time limit on how old the Gazette notification can be, or will any old one work?", "If I get the Gazette, how long will the name change take after submission? I want a clear timeline before I go through all that trouble.", "Fine — if you won''t change my name, I want to close my account. Can you help me with that instead?", "Who is your grievance officer? I want to formally escalate this right now."]'::jsonb,
  NOW()
);

-- ── Mock Call 3 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'Takeover Offer – Client Insists Despite Higher Market Price',
  'A client wants to apply for a takeover offer through Console/Kite. The policy allows takeover applications only when the market price is lower than the takeover price. In this case, the market price is higher, so the client must raise a support ticket instead of applying directly.',
  'You receive an inbound call. The client insists on applying for the takeover directly through the platform even though the market price is higher than the takeover price, and refuses to create a support ticket.',
  '["Explain the policy and the reason behind the price-based restriction clearly", "Empathise with the urgency of the live market situation", "Walk the client through the ticket process step by step", "Set realistic expectations on turnaround time", "Offer to stay on the call while the ticket is raised if possible"]'::jsonb,
  '["If I''m willing to proceed at a higher takeover price, that''s my financial decision to make — why is your system blocking me from doing that?", "You''re allowing it through Console when the market price is lower — so the system can process takeovers. Why is the same Console suddenly off-limits when the price is higher?", "What is the business logic behind this restriction? Is this a SEBI regulation or your internal risk policy? I want a clear answer.", "If I''m the one bearing the financial risk of a higher takeover price, why does your organisation get to decide whether I can proceed or not?", "Why can''t this be done directly — why does it have to go through a ticket? What additional check does a ticket add that can''t be done right now?", "Who reviews the ticket once I raise it? What is the exact approval process and who has the authority to approve it?", "What is the guaranteed turnaround time on the ticket? If there''s a time-sensitive market situation, a slow ticket process could cost me money — who is liable for that?", "Has anyone ever raised a ticket for this and had it approved? Or is the ticket just a way to say no politely?", "Can you explain to me in simple terms — at what exact price point does the system automatically allow the takeover versus when it gets blocked?", "Is this restriction applicable across all scrips and all clients, or are there exceptions for certain account types or trade volumes?", "If the market price fluctuates and drops below the takeover price while my ticket is being processed — will it automatically be approved then, or do I need to raise a fresh request?", "Is there a specific window or trading session during which this can be processed through the ticket route?", "I came to you with a clear instruction — execute my takeover. Instead, you''re telling me to raise a ticket and wait. How is that acceptable in a live market scenario?", "Every minute I wait, the market is moving. Who in your organisation is going to take responsibility if I miss the opportunity because of this process delay?", "I''ve been doing takeovers with you for years — why is this rule being applied to me now? Was I ever informed about this restriction?", "Can I speak to your dealing desk or risk team directly instead of going through a ticket? I want this resolved in real time.", "So your final answer is — either wait for a ticket approval or don''t do the takeover at all? Is that what you''re telling me?", "If I move my portfolio to another broker who can execute this without these restrictions, will you take ownership for that loss of business?", "Put it in writing that the delay in execution due to your ticket process is not your organisation''s liability — let''s see if you''re confident enough to do that."]'::jsonb,
  NOW()
);

-- ── Mock Call 4 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'NCRP Lien – Delayed Payment Charges on Frozen Funds',
  'A client calls about delayed payment charges on their account. The funds were marked as Lien following an NCRP complaint. The client has filed a police complaint and claims they are not at fault. Due to the lien, the account moved into debit and delayed payment charges were applied.',
  'You receive an inbound call. The client is outraged that their funds were frozen due to an NCRP complaint they claim is fraudulent, and that delayed payment charges have been levied on the resulting debit balance.',
  '["Empathise genuinely — the client is a victim in this situation", "Clearly explain the regulatory obligation behind the Lien (NCRP directive)", "Explain the NOC process accurately and which authority issues it", "Address the delayed payment charges with sensitivity and escalation path", "Commit to sending a written summary of the call and next steps"]'::jsonb,
  '["I am the victim here — someone filed a complaint against me fraudulently, and instead of protecting me, you''ve frozen my own money. How does that make any sense?", "I have already filed a police complaint proving I am not at fault. Why is that not enough for you to release my funds immediately?", "Did you even bother to verify the complaint before marking my funds as Lien? Or did you just act on it blindly without informing me?", "When exactly was the Lien marked, and why was I not notified immediately? I had to find out on my own — is that your standard process?", "On whose authority were my funds frozen? Was this your internal decision or a regulatory directive? I want that in writing.", "NCRP is a portal where anyone can file a complaint — does that mean any person can get my funds frozen just by filing something online? Where is the due diligence?", "What is the exact amount that has been marked as Lien? Is it my entire balance or only a specific amount linked to the complaint?", "Have you even looked at my account history? Does it show any suspicious activity that justifies this action against me?", "You''re telling me I need an NOC from authorities — but I''m the complainant, not the accused. Why am I running around getting documents to fix your action?", "Which specific authority needs to issue this NOC — the police, the cybercrime cell, or NCRP itself? I want an exact answer, not a vague response.", "What is the format of the NOC you need? If I go to the police station and they don''t know what to issue, who will guide them — will your team coordinate with them?", "Is there a deadline by which I need to submit this NOC? What happens to my funds if it takes longer than expected to obtain it?", "You froze my funds without my fault, and now on top of that you''re charging me delayed payment charges? How is that even legally justifiable?", "My funds were under Lien — I physically could not make payments even if I wanted to. How can you penalise me for a delay that your own action caused?", "I want a complete breakdown of these delayed payment charges — dates, amounts, and the reason each charge was applied. Send it to me right now.", "Who approved raising these charges on a Lien-marked account? I want that person''s name and designation.", "I don''t want this going to a regular escalation team — I want this on the desk of your Compliance Officer or Nodal Officer today. Can you make that happen?", "What is the guaranteed timeline for the escalation team to reverse these charges? I want a commitment, not a standard SLA response.", "If the escalation team does not reverse the charges, what is my next step — the consumer forum, SEBI SCORES, or the Banking Ombudsman? Tell me right now so I can start that process in parallel.", "I want everything discussed on this call — the Lien reason, the NOC requirement, and the charge reversal commitment — sent to me in an email before I hang up. Can you do that?"]'::jsonb,
  NOW()
);

-- ── Mock Call 5 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'Minor Account – Premature Blocking Before 18th Birthday',
  'A client''s daughter had her minor account blocked 15 days before her 18th birthday as part of the system''s majority-attainment process. The client argues the block should only trigger after she officially turns 18, and claims missed trading opportunities during those 15 days.',
  'You receive an inbound call. The parent is upset that their daughter''s minor account was blocked 15 days early, and is demanding accountability, a clear resolution timeline, and written confirmation.',
  '["Acknowledge the client''s frustration and validate the concern", "Explain the policy reason for early blocking (system-triggered majority process)", "Clearly outline the unblocking and minor-to-major conversion steps", "Give a realistic commitment on resolution timeline", "Offer to send written confirmation of the process and timeline"]'::jsonb,
  '["My daughter''s account was blocked 15 days before her birthday — can you show me exactly which policy or clause says you are authorised to block an account before she even turns 18? Because as far as I know, she was still a minor and the account should have remained active.", "Those 15 days may seem small to you, but there were market movements and investment opportunities during that period that we completely missed out on. Who in your organisation is going to take accountability for that financial loss?", "I have been a loyal client for years. Is this how you treat long-standing customers — by blocking accounts without even sending a prior notice or warning? Why was I not informed before this action was taken?", "If your system triggered this block automatically, then clearly there is a flaw in your process. How do I know this kind of error won''t happen again with my other accounts or future transactions?", "I want this escalated right now. I don''t want to keep explaining the same thing to different agents. Can you confirm who the decision-making authority is on this matter and get them on the call?", "Your team blocked the account saying she is turning 18 — but on the date of blocking, she was legally still a minor. Doesn''t that mean you acted outside your authority? Shouldn''t the block only apply after she completes 18 years?", "You are telling me the unblocking will be handled by the Minor team — so the same team that made this error is the one fixing it? How can I trust that the resolution will be accurate and complete this time?", "What is the exact timeline for this unblocking? I need a commitment — not an estimate, not as soon as possible. Can you give me a date and time by which the account will be fully operational?", "Once the account is unblocked and my daughter turns 18, what exactly is the process to convert it from a minor to a major account? How long will that take, and will there be any further interruptions to the account during that transition?", "I want written confirmation of everything you''ve told me today — the reason for the premature block, the resolution steps, the timeline, and the name of the person responsible for ensuring this is fixed. Can you arrange that for me right now?"]'::jsonb,
  NOW()
);

-- ── Mock Call 6 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'Emergency Withdrawal – Blocked Due to Open Long Index Options',
  'A client requests an instant withdrawal citing a personal emergency. Their account has an open long index options position. Policy disallows instant withdrawal with open positions. The client argues that long options have limited (capped) downside and insists the withdrawal should be allowed.',
  'You receive an inbound call. The client is in an urgent situation and demands immediate fund release, arguing that their open long index options position does not justify blocking the withdrawal.',
  '["Empathise deeply with the emergency situation", "Explain the policy on withdrawals with open positions clearly and calmly", "Acknowledge the limited-loss nature of long options while holding firm on policy", "Walk through the emergency payout request process step by step", "Escalate proactively if the situation genuinely warrants it"]'::jsonb,
  '["I have been waiting for over an hour now and nobody has given me a clear answer. Why does your platform even allow me to put my money in if you can''t give it back to me when I need it the most?", "I understand there''s something called limited loss on my position — does that mean my money is already safe? Then why can''t you just release it to me right now?", "I never signed anything that said my funds would be locked. Where exactly in your terms does it say you can block my withdrawal? Can you read it out to me?", "If I close my options position right now and take the loss, will you process my withdrawal immediately? Or are you going to find another reason to hold my money?", "This is a genuine medical emergency. If something happens to my family because I couldn''t access my funds, is your company going to take responsibility for that?", "You keep saying funds team — who exactly are these people? Can I speak to them directly right now? Why are you the middleman here?", "How long does this so-called emergency payout request actually take? Because if it''s going to take 24 hours, it''s completely useless to me.", "I have seen other brokers allow instant withdrawals even on open positions. Why is your platform so behind? Is this a technical limitation or just a policy to hold onto client money longer?", "What guarantee do I have that once you request this emergency payout, it will actually be approved? What happens if it gets rejected — what are my options then?", "I want this escalated to your senior management right now. I don''t want to wait for a callback. What is the direct contact of your compliance or grievance team, and what is the turnaround time for a formal complaint?"]'::jsonb,
  NOW()
);

-- ── Mock Call 7 ────────────────────────────────────────────
INSERT INTO topics (module, title, description, scenario, checklist, bot_script, created_at)
VALUES (
  'mock-call',
  'Pledged Stocks – Undisclosed Aging Debit Balance & Trading Losses',
  'A client pledged stocks after calling support but was not informed about an existing aging debit balance. They used the collateral margin to trade, incurred losses, and are now demanding a refund — claiming the support representative''s omission directly caused the losses.',
  'You receive an inbound call. The client is demanding a full refund for trading losses, alleging that your support team failed to disclose an aging debit balance before they pledged their stocks and began trading.',
  '["Acknowledge the client''s frustration without admitting liability prematurely", "Explain the process for investigating the call recording", "Set clear expectations on investigation timelines", "Empathise with the financial impact while explaining the refund process", "Escalate to the appropriate team and give the client an owner''s name and TAT"]'::jsonb,
  '["I specifically called your team before pledging my stocks and asked all the necessary questions. Why was I never told that there was an existing debit balance on my account? Isn''t it your representative''s job to disclose everything before I make a financial decision?", "Because your sales manager hid this debit balance from me, I went ahead and traded, made losses, and now my collateral is blocked. How is any of this my fault? Your negligence caused my losses — why should I bear them?", "I have the call recording of when I spoke to your representative before pledging. If I pull that up and prove that the debit balance was never mentioned, will your company refund my losses in full? What is your stand on that?", "You are telling me I cannot trade using my collateral because of a debit balance that I didn''t even know existed. So essentially you took my pledged stocks, let me trade, and then pulled the rug from under me. How is that not a fraudulent business practice?", "If your sales manager had informed me about the debit balance before I pledged, I would have cleared it first or never pledged at all. Can you calculate exactly how much loss I have made because of this missing information and tell me why that should not be refunded?", "I want to know — is it a regulatory requirement for your representatives to disclose all outstanding dues and liabilities before a client pledges securities? Because if it is, your company has clearly violated that and I will be taking this to SEBI.", "Right now my stocks are pledged with you, I have a debit balance I didn''t know about, and I can''t even trade. I am completely stuck. What exactly are you going to do to fix this situation today — not tomorrow, not after an investigation — today?", "I have been a loyal client for years. I trusted your representative''s advice and look where it has gotten me. What is the point of having a relationship manager if they don''t give me complete information at the most critical time? Who is accountable here?", "You keep saying you will investigate and check the call recording. How long is this investigation going to take? And while your investigation is going on, my capital is stuck and I am missing market opportunities every single day. Who is compensating me for that?", "If your internal investigation confirms that your sales manager did not disclose the debit balance — which I am 100% sure it will — what is the exact process for me to claim a refund? I want the escalation path, the TAT, and the name of the person who will own this case. I am not closing this call without that."]'::jsonb,
  NOW()
);

-- ============================================================
--  DONE. All 7 Mock Call topics inserted.
--  Note: If you previously inserted "Pledged Stocks" manually,
--  go to Admin → Topics and delete the duplicate.
-- ============================================================
